name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-18.04
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:12.24.1-alpine3.10
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: Log Node version
        uses: docker://node:12.24.1-alpine3.10
        with:
          entrypoint: /bin/node
          args: -v
##  multiple_services:
##    runs-on: ubuntu-18.04
##    services:
##      app:
##        image: alialaa17/node-api
##        ports:
##          - 3001:3000
##      mongo:
##        image: mongo
##        ports:
##          - 27017:27017
##    steps:
##      - name: Post a user
##        run: "curl -X POST http://localhost:3001/api/user
##          -H 'Content-Type: application/json' -d '
##          {\"username\": \"hello\", \"address\": \"afvdv\"'}"
##      - name: Get Users
##        run: curl http://localhost:3001/api/users
#  node-docker:
#    runs-on: ubuntu-18.04
####    container:
#      image: node:13.5.0-alpine3.10
#    steps:
#      - name: Log Node version
#        run: |
#          node -v
#          cat /etc/os-release