name: Actions Workflow

on:
  repository_dispatch:
    types:
      - build
  push:
  pull_request:
    types:
      - closed
      - assigned
      - opened
      - reopened

jobs:
  run-shell-command:
    runs-on: ubuntu-18.04
    steps:
      - name: List files
        run: ls
      - name: Checkout
        uses: actions/checkout@v1
