name: Actions Workflow

on:
  repository_dispatch:
    types:
      - build
  push:
    branches:
      - main
      - "features/*" # Matches any string like features/featureA except features/other/otherFeatureA
      - "features/**"# Marches everthing
      - "!features/featC"# Marches everthing
    tags:
      - v1
    paths-ignore:
      - "docs/**"
  pull_request:
    types:
      - closed
      - assigned
      - opened
      - reopened

jobs:
  run-shell-command:
    runs-on: ubuntu-18.04
    steps:
      - name: List files
        run: ls
      - name: Checkout
        uses: actions/checkout@v1
  run-powershell-command:
    runs-on: windows-2022
    steps:
      - name: Directory List PowerShell
        run: Get-Location